// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4sF8oMi8QnpUAsRvTvcQfXxc-nREx3I',
    appId: '1:218385830574:web:f5d5fb6ee8c9c00478933f',
    messagingSenderId: '218385830574',
    projectId: 'memorisevocabulary',
    authDomain: 'memorisevocabulary.firebaseapp.com',
    storageBucket: 'memorisevocabulary.appspot.com',
    measurementId: 'G-M21MJ1K2C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9esxEEEyME1jlJdmEgZ6A8F_uQbVPhhc',
    appId: '1:218385830574:android:61ab44c1483dc7f978933f',
    messagingSenderId: '218385830574',
    projectId: 'memorisevocabulary',
    storageBucket: 'memorisevocabulary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLfAQK5rOnABvx2FuBdQWWERIQA5VKfX4',
    appId: '1:218385830574:ios:b6fd84af2e39dddd78933f',
    messagingSenderId: '218385830574',
    projectId: 'memorisevocabulary',
    storageBucket: 'memorisevocabulary.appspot.com',
    iosBundleId: 'com.example.xbcodebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLfAQK5rOnABvx2FuBdQWWERIQA5VKfX4',
    appId: '1:218385830574:ios:b6fd84af2e39dddd78933f',
    messagingSenderId: '218385830574',
    projectId: 'memorisevocabulary',
    storageBucket: 'memorisevocabulary.appspot.com',
    iosBundleId: 'com.example.xbcodebase',
  );
}
